### ISSUE TITLE
Todo List

### ISSUE THREAD

**Issue by BradleyJinks** [BradleyJinks/megapics#1]
Todo

- [ ] Search Functionality (maybe)
- [ ] Client And Server Validation
- [ ] Search Functionality (maybe)
- [ ] pagination
- [ ] Email Design
- [ ] Email Send Button for newsletter
- [ ] Full Site navigation
- [ ] Add links and text to footer
- [ ] Fill all pages with the correct content
